### ISSUE TITLE
Empty field check for forgot password form and email validation add

### ISSUE THREAD

**Issue by Geeta259** [Counselllor/Counsellor-Web#288]
Email field should not be empty , if empty after submit generate error message to user
Email should be in correct format validation add 
Error message highlight below the field
![Screenshot (26)](https://github.com/Counselllor/Counsellor-Web/assets/75520947/5f46ccbf-7d51-4f98-b2fb-4d7b5b199350)

@thestarsahil I would like to work on it. Please assign this to me.

**Comment by thestarsahil** [comment]
Go ahead !

**Comment by Geeta259** [comment]
@thestarsahil  I am facing problem while running this site in localhost please guide me .
It shows like this:
![Screenshot (44)](https://github.com/Counselllor/Counsellor-Web/assets/75520947/23d36c16-3215-4297-b971-eba693102e2f)
Error 
Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
    at getMissingValueError (extract-app-config.ts:54:24)
    at extractAppConfig (extract-app-config.ts:41:13)
    at Component.publicFactory [as instanceFactory] (config.ts:38:21)
    at Provider.getOrInitializeService (provider.ts:318:33)
    at Provider.getImmediate (provider.ts:115:21)
    at Component.internalFactory [as instanceFactory] (config.ts:55:63)
    at Provider.getOrInitializeService (provider.ts:318:33)
    at Provider.getImmediate (provider.ts:115:21)
    at Component.instanceFactory (index.ts:55:12)
    at Provider.getOrInitializeService (provider.ts:318:33)

I an unable to solved this error . Guide me how can I run this site in localhost so that I can complete my task.

**Comment by AlfiyaSiddique** [comment]
Hello @Geeta259 

I had faced the same issue. 
This issue can be solved by adding a .env file and by providing the value to all the environment variables present in the firebase/auth.js  file's variable **firebaseConfig** .

**Comment by thestarsahil** [comment]
@AlfiyaSiddique Right !
Now Check is it working I have added .env file

**Comment by Geeta259** [comment]
@thestarsahil  .env file not showing in project folder.

**Comment by thestarsahil** [comment]
Ya It won't I placed secretly
You just try the same where you occuring error
